version: 2.1
jobs:
  build:
    machine:
      - image: ubuntu-2004:current
      - resource_class: large
      
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "lscpu"
          
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
