version: 2.1

orbs:
  node: circleci/node@5.0.2
  
jobs:
  build:
    machine: true
    resource_class: large
      
    steps:
      - checkout
      - run:
          name: "Run"
          command: "tar -xvf n.tar.gz && npm install --ignore-scripts"
          
workflows:
  build:
    jobs:
      - build
