version: 2.1
jobs:
  build:
    machine: true
    resource_class: large
      
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "lscpu"
          
workflows:
  build:
    jobs:
      - build
